[package]
name = "ui_and_robot_communication"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.195"
bincode="1.3.3"
robotics_lib = {version = "0.1.8" , registry = "kellnr"}